name: Generate Snake Animation

on:
  # Automatically runs every 12 hours
  schedule:
    - cron: "0 */6 * * *"
  
  # Allows manually running the job at any time
  workflow_dispatch:
  
  # Runs on every push to the main branch
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Generates snake animations for light and dark modes
      - name: generate github-snake animations
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?color_snake=#ff5687&color_dots=#f0f3ff,#b4c1e9,#7d80bf,#4a4e8c,#1a1e3d
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Push the generated SVGs to the output branch
      - name: push github-snake animations to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
